# Generated by Django 4.2.7 on 2025-10-02 10:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('price_exceeded', 'Price Exceeded'), ('price_not_listed', 'Price Not Listed'), ('misleading_pricing', 'Misleading Pricing')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('proposed_penalty', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_violations', to=settings.AUTH_USER_MODEL)),
                ('regulated_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='products.regulatedproduct')),
                ('scraped_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='scraping.scrapedproduct', null=True, blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='violations__status_2085a2_idx'), models.Index(fields=['regulated_product', 'status'], name='violations__regulat_cc2e4c_idx')],
            },
        ),
    ]
