# Generated by Django 4.2.7 on 2025-10-07 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_scrapingwebsite_fallback_to_selenium_and_more'),
        ('products', '0002_ratelistupload'),
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationCheckReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now_add=True)),
                ('has_violation', models.BooleanField(default=False)),
                ('compliance_status', models.CharField(choices=[('ok', 'Compliant'), ('violation', 'Violation'), ('no_match', 'No Matching Regulated Product')], default='no_match', max_length=20)),
                ('price_difference', models.DecimalField(blank=True, decimal_places=2, help_text='Difference between scraped and regulated price', max_digits=10, null=True)),
                ('percentage_difference', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage difference from regulated price', max_digits=5, null=True)),
                ('violation_severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20, null=True)),
                ('proposed_penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('regulated_product', models.ForeignKey(blank=True, help_text='Regulated product (null if no match found)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_reports', to='products.regulatedproduct')),
                ('scraped_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_reports', to='scraping.scrapedproduct')),
                ('violation_record', models.ForeignKey(blank=True, help_text='Associated violation record if any', null=True, on_delete=django.db.models.deletion.SET_NULL, to='violations.violation')),
            ],
            options={
                'ordering': ['-check_date'],
                'indexes': [models.Index(fields=['compliance_status', 'check_date'], name='violations__complia_d70020_idx'), models.Index(fields=['scraped_product', 'check_date'], name='violations__scraped_4c3b7a_idx'), models.Index(fields=['has_violation', 'check_date'], name='violations__has_vio_1b983e_idx')],
                'unique_together': {('regulated_product', 'scraped_product')},
            },
        ),
    ]
