# Generated by Django 4.2.7 on 2025-10-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='session_type',
            field=models.CharField(choices=[('api', 'API Session'), ('admin', 'Admin Session')], default='api', help_text='Type of session', max_length=10),
        ),
    ]
