# Generated by Django 4.2.7 on 2025-10-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingjob',
            name='auto_start',
            field=models.BooleanField(default=True, help_text='Automatically start job when created'),
        ),
        migrations.AddField(
            model_name='scrapingjob',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When to start the scraping job', null=True),
        ),
        migrations.AlterField(
            model_name='scrapingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
