# Generated by Django 4.2.7 on 2025-10-06 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_scrapingjob_auto_start_scrapingjob_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingjob',
            name='current_progress',
            field=models.TextField(blank=True, help_text='Current progress message'),
        ),
        migrations.CreateModel(
            name='ScrapingJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scraping.scrapingjob')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
