# Generated by Django 4.2.7 on 2025-10-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_scrapingjob_current_progress_scrapingjoblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingwebsite',
            name='fallback_to_selenium',
            field=models.BooleanField(default=True, help_text='Fall back to Selenium if direct requests fail'),
        ),
        migrations.AddField(
            model_name='scrapingwebsite',
            name='selenium_config',
            field=models.JSONField(default=dict, help_text='Selenium-specific configuration overrides'),
        ),
        migrations.AddField(
            model_name='scrapingwebsite',
            name='use_selenium',
            field=models.BooleanField(default=False, help_text='Use Selenium for scraping this website'),
        ),
    ]
