# Generated by Django 4.2.7 on 2025-10-06 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateListUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/description of the rate list', max_length=255)),
                ('pdf_file', models.FileField(help_text='Upload PDF rate list', upload_to='rate_lists/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_products', models.PositiveIntegerField(default=0, help_text='Total products found in PDF')),
                ('imported_products', models.PositiveIntegerField(default=0, help_text='Products successfully imported')),
                ('errors', models.JSONField(blank=True, default=list, help_text='Processing errors')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_rate_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rate List Upload',
                'verbose_name_plural': 'Rate List Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
